/**
 * @file Script to generate theme registry TypeScript file
 *
 * Reads from themes-catalog.json and generates src/examples/themes/generated-themes.ts
 */
import { writeFileSync } from "node:fs";

import themesCatalog from "./themes-catalog.json";

const OUTPUT_PATH = "src/examples/themes/generated-themes.ts";

type ThemeCatalogEntry = {
  id: string;
  label: string;
  description: string;
  cssFile: string | null;
};

function generateThemeRegistry(): void {
  const themes = themesCatalog.themes as ThemeCatalogEntry[];

  // Generate TypeScript content
  const themeIds = themes.map((t) => `  | "${t.id}"`).join("\n");

  const themeEntries = themes
    .map((theme) => {
      const cssPath = theme.cssFile ? `/themes/${theme.cssFile}` : "";
      return `  {
    id: "${theme.id}",
    label: "${theme.label}",
    description: "${theme.description}",
    cssPath: "${cssPath}",
  }`;
    })
    .join(",\n");

  const content = `/**
 * @file Auto-generated theme definitions
 *
 * DO NOT EDIT THIS FILE DIRECTLY.
 * Edit scripts/themes-catalog.json and run: bun run generate:theme-registry
 */

export type NodeEditorThemeId =
${themeIds};

export type NodeEditorTheme = {
  id: NodeEditorThemeId;
  label: string;
  description: string;
  cssPath: string;
};

export const GENERATED_THEMES: NodeEditorTheme[] = [
${themeEntries},
];
`;

  writeFileSync(OUTPUT_PATH, content, "utf-8");

  console.log(`✅ Generated theme registry at ${OUTPUT_PATH}`);
  console.log(`   ${themes.length} themes defined`);
}

try {
  generateThemeRegistry();
} catch (error) {
  console.error("❌ Error generating theme registry:", error);
  process.exit(1);
}
